from datetime import datetime
from src.extensions import db

class SeismicEvent(db.Model):
    __tablename__ = "seismic_events"

    id = db.Column(db.Integer, primary_key=True)
    seiscomp_parent_oid = db.Column(db.String(50))
    table_name = db.Column(db.String(50))
    mKEY = db.Column(db.String(50))
    eq_key = db.Column(db.String(50))
    origin_time = db.Column(db.DateTime)
    origin_msec = db.Column(db.Integer)
    time_uncertainty = db.Column(db.Float)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    depth = db.Column(db.Float)
    region_old = db.Column(db.String(255))
    region_ge = db.Column(db.String(255))
    region_en = db.Column(db.String(255))
    area = db.Column(db.String(255))
    station_record_count = db.Column(db.Integer)
    station_used_count = db.Column(db.Integer)
    phases_count = db.Column(db.Integer)
    phases_used_count = db.Column(db.Integer)
    gap = db.Column(db.Float)
    station_min_distance = db.Column(db.Float)
    epicenter_uncertainty = db.Column(db.Float)
    latitude_uncertainty = db.Column(db.Float)
    longitude_uncertainty = db.Column(db.Float)
    depth_uncertainty = db.Column(db.Float)
    intensity = db.Column(db.Float)
    vmId = db.Column(db.Integer)
    shake_source = db.Column(db.String(50))
    info_ge = db.Column(db.Text)
    info_en = db.Column(db.Text)
    important = db.Column(db.String(10))
    comment = db.Column(db.Text)
    time_hypocenter_program = db.Column(db.String(50))
    creator_id = db.Column(db.Integer)
    editor_id = db.Column(db.Integer)
    last_edit_time = db.Column(db.DateTime, default=datetime.utcnow)